export const orbitalSequence = [
  { layer: 1, sub: "s", max: 2 },
  { layer: 2, sub: "s", max: 2 },
  { layer: 2, sub: "p", max: 6 },
  { layer: 3, sub: "s", max: 2 },
  { layer: 3, sub: "p", max: 6 },
  { layer: 4, sub: "s", max: 2 },
  { layer: 3, sub: "d", max: 10 },
  { layer: 4, sub: "p", max: 6 },
  { layer: 5, sub: "s", max: 2 },
  { layer: 4, sub: "d", max: 10 },
  { layer: 5, sub: "p", max: 6 },
  { layer: 6, sub: "s", max: 2 },
  { layer: 4, sub: "f", max: 14 },
  { layer: 5, sub: "d", max: 10 },
  { layer: 6, sub: "p", max: 6 },
  { layer: 7, sub: "s", max: 2 },
  { layer: 5, sub: "f", max: 14 },
  { layer: 6, sub: "d", max: 10 },
  { layer: 7, sub: "p", max: 6 },
];
